name: Automatizaci贸n de Script
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Descarga tu c贸digo
      - name: Dar permisos de ejecuci贸n
        run: chmod +x deploy.sh # Gesti贸n de permisos
      - name: Ejecutar script
        run: ./deploy.sh
